const express = require('express');

const app = express();
const mongoose = require('mongoose');
require('dotenv').config();

const { PORT = 3000 } = process.env;

const userRouter = require('./routes/users');
const articleRouter = require('./routes/articles');
const auth = require('./middlewares/auth');

const { login, createUser } = require('./controllers/userControllers');

const helmet = require('helmet');
const { celebrate, Joi, errors } = require('celebrate');
const { requestLogger, errorLogger } = require('./middlewares/logger');

const cors = require('cors');

mongoose.connect('mongodb://localhost:27017/practicum_final', {
  useNewUrlParser: true,
  useCreateIndex: true,
  useFindAndModify: false,
  useUnifiedTopology: true,
});

app.use(express.json());

// protects app from web vulnerabilities by setting HTTP headers
app.use(helmet());
app.use(cors());
app.options('*', cors());
// enabling the winston request logger
app.use(requestLogger);

app.post(
  '/signin',
  celebrate({
    body: Joi.object().keys({
      email: Joi.string().required().email(),
      password: Joi.string().required().min(8),
    })
      .unknown(true),
  }),
  login,
);
app.post(
  '/signup',
  celebrate({
    body: Joi.object().keys({
      email: Joi.string().required().email(),
      password: Joi.string().required().min(8),
    })
      .unknown(true),
  }),
  createUser,
);

app.use('/', auth, userRouter);
app.use('/', auth, articleRouter);

app.get('*', () => {
  throw new NotFoundError('Requested resource not found');
});

// enable winston error logger
app.use(errorLogger);

// celebrate error handler - only handles errors generated by celebrate
app.use(errors());

app.use((err, req, res, next) => {
  const { statusCode, message } = err;
  res.status(statusCode).send({
    message:
      statusCode === 500 ? 'An error occurred on the server' : message,
  });
  next();
});

app.listen(PORT, () => {
  // if everything works fine, the console will show which port the application is listening to
  console.log(`App listening at port ${PORT}, k byeBYE!`);
});
